### ISSUE TITLE
Could not pass event PlayerInteractEvent to Wild v3.8.2

### ISSUE THREAD

**Issue by Volander** [Qballl/WildernessTp#9]
[Server thread/ERROR]: Could not pass event PlayerInteractEvent to Wild v3.8.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.Qball.Wild.Listeners.BlockClickEvent.onBlockClick(BlockClickEvent.java:39) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-aad97c4-4602331]
	... 17 more

**Comment by Qballl** [comment]
I'm aware of this issue and have fixed it I believe in a dev build but have not been able to produce this error my test server with the older version so I am unsure if I have fixed it. Do you know what events cause the error?

**Comment by Qballl** [comment]
Im gonna close this and label it as fixed if it isnt just comment on the issue and I'll reopen

**Comment by Volander** [comment]
Where can I get this dev version to test it out?

**Comment by Qballl** [comment]
You can download it from the target folder on git sorry for late reply hadn't checked my email

**Comment by Volander** [comment]
Still getting these errors using your dev version.

http://pastebin.com/c7Pw5A54

 - Volander

**Comment by Qballl** [comment]
There is no line number for either error despite there being two errors of the same so can you tell me what a player is doing at the time this error is thrown?

**Comment by Qballl** [comment]
Can you please ensure you have the full error by getting it from the latest log file, this is missing the very important information what class and what line.

**Comment by Qballl** [comment]
Fixed in the latest version
